apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nginx","example-webhook-enabled":"true"},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":90,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"}}}
  creationTimestamp: "2024-01-29T06:38:26Z"
  labels:
    app: nginx
    author: minikube-user
    example-webhook-enabled: "true"
    operation: UPDATE
  name: nginx-service
  namespace: default
spec:
  clusterIP: 10.111.255.173
  clusterIPs:
  - 10.111.255.173
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 90
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
